---

- name: install docker-compose
  copy: src=resources/docker-compose.{{ version.docker_compose }}
        dest=/usr/local/bin/docker-compose
        owner=root
        group=root
        mode=755
