---

# Fetch resources and set variables used by system
- include_vars: secrets.yml
  tags:
    - always

# Resource downloader depends on docker
- include: docker.yml tags=docker
- include: resource-downloader.yml tags=always

# Download and install programs
- include: common.yml tags=common
- include: android.yml tags=android
- include: docker-compose.yml tags=docker
- include: resource-downloader.yml tags=download
- include: java.yml tags=java
- include: kubernetes.yml tags=kubernetes
- include: openshift.yml tags=openshift
- include: rclone.yml tags=rclone
- include: terraform.yml tags=terraform
- include: vagrant.yml tags=vagrant
- include: virtual-machine.yml
  tags:
    - vm
    - virtualbox
    - vmware