---

- name: install virtualbxo apt repo key
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc

- name: install virtualbox repository with latest stable version
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian vivid contrib' state=present
  notify:
    - apt update

- name: install virtualbox
  apt: name=virtualbox-5.0 state=latest

#- name: install vmware
#  apt: deb=vmware.deb
#  tags: vmware